---
title: "Allocation"
output:
    html_document:
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: pygments
        code_folding: hide
        fig_width: 9
        fig_height: 3
        css: style.css
params:
    datadir: "./data"
    graphdir: "./graphs"
    macrodir: "./macros"
    tabledir: "./tables"
---

```{r echo = FALSE, warning=FALSE, message=FALSE}
## https://bookdown.org/yihui/rmarkdown-cookbook/source-script.html
source("analysis.R", local = knitr::knit_global())
MacGen <- LatexMacroGenerator$new(params$macrodir)
```

## Object Counts

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
allocation <-
    allocation %>%
    select(type, count = allocated) %>%
    filter(!(type %in% c("missing", "null", "unbound", "bytecode", 
                         "miscellaneous", "special", "builtin", "dot",
                         "char", "weakref", "pairlist")))

datatable(allocation)

OTHER_ALLOCATION_CUTOFF <- 40000000

other_allocation <-
    allocation %>% 
    filter(count <= OTHER_ALLOCATION_CUTOFF) %>%
    print() %>%
    summarize(type = "other", count = sum(count))

allocation <-
    allocation %>%
    filter(count > OTHER_ALLOCATION_CUTOFF) %>%
    bind_rows(other_allocation)

allocation_table <-
    allocation %>%
    mutate(type = str_to_title(type)) %>%
    arrange(desc(count)) %>%
    mutate(count = label_number_si(accuracy = 0.1)(count))
    
datatable(allocation_table)

macros <- MacGen$from_table(allocation_table, "type", "count", "ObjCnt")

allocation_table %>%
add_column(macro = macros) %>%
latex_table(
    function(type, count, macro) {
        sprintf("%s&%s", type, macro)
    }
) %>%
cat()
```

## API Usage

```{r, eval = TRUE}
fix_command_names <- function(names) {
    names %>%
    str_to_title() %>%
    str_replace_all(fixed("."), "Dot") %>%
    str_replace_all(fixed("0"), "Zero") %>%
    str_replace_all(fixed("2"), "Two") %>%
    str_replace_all(fixed("~"), "Tilde") %>%
    str_replace_all(fixed("[["), "DBrack") %>%
    str_replace_all(fixed("$"), "Dollar") %>%
    str_replace_all(fixed("<-"), "Assign")
}

## add new.env counts
api_usage <- add_row(api_calls, fun_name = "new.env", calls = sum(new_env$count))
    
## add objects function count as 0 if not already present
if (!("objects" %in% api_usage$fun_name)) {
    api_usage <- add_row(api_usage, fun_name = "objects", calls = 0)
}

api_usage_table <-
    api_calls %>%
    mutate(fun_name = if_else(fun_name == "env2list", "as.list", fun_name)) %>%
    filter(!(fun_name %in% c("Argument", "Return", "L", "A", "D", "R"))) %>%
    mutate(name = fix_command_names(fun_name)) %>%
    arrange(desc(calls)) %>%
    mutate(calls = label_number_si(accuracy = 0.1)(calls))

macros <- MacGen$from_table(api_usage_table, "name", "calls", "CallCnt")

api_usage_table %>%
add_column(macro = macros) %>%
latex_table(
    function(fun_name, calls, name, macro) {
        sprintf("\\texttt{%s}&%s", latex_sanitize(fun_name), macro)
    }
) %>%
cat()
```
